### PR TITLE
Fix/correct http error

### PR DESCRIPTION
**Pull request by gdchamal**
Use of colander for user parameter validation and manage better HTTP errors

### CODE REVIEW

**Comment by esion** [comment]
got this error after updating (colander installed I guess)

~~~
2015-10-16 11:53:21,564 ERROR [waitress][waitress] Exception when serving /api/v1/authentications
Traceback (most recent call last):
  File "/home/workspace/caliopen/venv/local/lib/python2.7/site-packages/waitress-0.8.10-py2.7.egg/waitress/channel.py", line 336, in service
    task.service()
  File "/home/workspace/caliopen/venv/local/lib/python2.7/site-packages/waitress-0.8.10-py2.7.egg/waitress/task.py", line 169, in service
    self.execute()
  File "/home/workspace/caliopen/venv/local/lib/python2.7/site-packages/waitress-0.8.10-py2.7.egg/waitress/task.py", line 388, in execute
    app_iter = self.channel.server.application(env, start_response)
  File "/home/workspace/caliopen/venv/local/lib/python2.7/site-packages/pyramid-1.5.7-py2.7.egg/pyramid/router.py", line 242, in __call__
    response = self.invoke_subrequest(request, use_tweens=True)
  File "/home/workspace/caliopen/venv/local/lib/python2.7/site-packages/pyramid-1.5.7-py2.7.egg/pyramid/router.py", line 217, in invoke_subrequest
    response = handle_request(request)
  File "/home/workspace/caliopen/venv/local/lib/python2.7/site-packages/pyramid-1.5.7-py2.7.egg/pyramid/tweens.py", line 46, in excview_tween
    response = view_callable(exc, request)
  File "/home/workspace/caliopen/venv/local/lib/python2.7/site-packages/pyramid-1.5.7-py2.7.egg/pyramid/config/views.py", line 377, in rendered_view
    context)
  File "/home/workspace/caliopen/venv/local/lib/python2.7/site-packages/pyramid-1.5.7-py2.7.egg/pyramid/renderers.py", line 428, in render_view
    return self.render_to_response(response, system, request=request)
  File "/home/workspace/caliopen/venv/local/lib/python2.7/site-packages/pyramid-1.5.7-py2.7.egg/pyramid/renderers.py", line 451, in render_to_response
    result = self.render(value, system_values, request=request)
  File "/home/workspace/caliopen/venv/local/lib/python2.7/site-packages/pyramid-1.5.7-py2.7.egg/pyramid/renderers.py", line 447, in render
    result = renderer(value, system_values)
  File "/home/workspace/caliopen/api.base/caliopen/api/base/renderer.py", line 51, in __call__
    return json.dumps(data, cls=JSONEncoder)
  File "/home/workspace/caliopen/venv/local/lib/python2.7/site-packages/simplejson-3.8.0-py2.7-linux-x86_64.egg/simplejson/__init__.py", line 397, in dumps
    **kw).encode(obj)
  File "/home/workspace/caliopen/venv/local/lib/python2.7/site-packages/simplejson-3.8.0-py2.7-linux-x86_64.egg/simplejson/encoder.py", line 275, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/home/workspace/caliopen/venv/local/lib/python2.7/site-packages/simplejson-3.8.0-py2.7-linux-x86_64.egg/simplejson/encoder.py", line 357, in iterencode
    return _iterencode(o, 0)
  File "/home/workspace/caliopen/api.base/caliopen/api/base/renderer.py", line 33, in default
    return super(JSONEncoder, self).default(obj)
  File "/home/workspace/caliopen/venv/local/lib/python2.7/site-packages/simplejson-3.8.0-py2.7-linux-x86_64.egg/simplejson/encoder.py", line 252, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: CredentialException(u'Invalid user',) is not JSON serializable
~~~

**Comment by gdchamal** [comment]
Will fix asap. Thanks

**Comment by gdchamal** [comment]
still got bad habits with others python web frameworks that pyramid avoid, for sake I think.

**Comment by esion** [comment]
works like a charm

**Pull request merged**
